# Generated by Django 2.2 on 2019-04-24 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cmp_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
                ('created', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
                ('currentCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ink.Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpDate',
            fields=[
                ('id1', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('left', models.DateTimeField(blank=True, null=True)),
                ('cmp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ink.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompOrEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('employee', 'employee'), ('company', 'company')], max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ink.Company')),
                ('currentEmployees', models.ManyToManyField(to='Ink.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployementHistory',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Ink.Employee')),
                ('companiesAppliedToHistory', models.ManyToManyField(to='Ink.Company')),
            ],
        ),
    ]
