# Generated by Django 2.2 on 2019-04-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdate',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ink.Employee'),
        ),
    ]
